services:
  sighook:
    image: denfish/bot-sighook:2.44
    env_file:
      - ./.env_tradebot
    volumes:
      - /home/denfish/BotTrader/.env_tradebot:/app/.env
      - /home/denfish/BotTrader/data:/app/data  # location for SQLite DB
      - /home/denfish/BotTrader/logs/sender/sender_logs:/app/logs/sender/sender_logs
    ports:
      - "5001:5001"
    networks:
      - traderbot_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Maximum log file size
        max-file: "3"     # Number of log files to retain

  webhook:
    image: denfish/bot-webhook:2.44
    env_file:
      - ./.env_tradebot
    volumes:
      - /home/denfish/BotTrader/.env_tradebot:/app/.env
      - /home/denfish/BotTrader/data:/app/data
      - /home/denfish/BotTrader/logs/listener/listener_logs:/app/logs/listener/listener_logs
    ports:
      - "5000:5000"
    networks:
      - traderbot_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traderbot_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/29"




