version: '3.7'
#docker-compose.network.digital_ocean.yaml
services:
  sighook:
    image: denfish/bot-sighook:2.22
    env_file:
      - ./.env_tradebot  # Path relative to the context
    volumes:
      - /home/denfish/BotTrader/.env_tradebot:/app/.env  #"./local_env_path/.env:/app/
      - /home/denfish/BotTrader/data:/data
      - /home/denfish/BotTrader/logs/sender/sender_logs:/app/logs/sender/sender_logs
    ports:
      - "5001:5001"
    networks:
      - traderbot_network
    restart: always
  webhook:
    image: denfish/bot-webhook:2.22
    env_file:
      - ./.env_tradebot  # Path relative to the context
    volumes:
      - /home/denfish/BotTrader/.env_tradebot:/app/.env  #"./local_env_path/.env:/app/
      - /home/denfish/BotTrader/data:/app/data
      - /home/denfish/BotTrader/logs/listener/listener_logs:/app/logs/listener/listener_logs
      - /home/denfish/BotTrader/logs/flask_logs:/app/logs/flask_logs
    ports:
      - "5000:5000"
    networks:
      - traderbot_network
    restart: always
networks:
  traderbot_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/29"

