services:
  sighook:
    image: denfish/bot-sighook:latest
    volumes:
      - /home/denfish/BotTrader/.env_tradebot:/app/.env_tradebot
      - /home/denfish/BotTrader/data:/app/data  # location for SQLite DB
      - /home/denfish/BotTrader/Shared_Utils:/app/Shared_Utils  # Mount the Shared_Utils directory
      - /home/denfish/BotTrader/sighook/sighook_api_key.json
    env_file:
      - ./.env_tradebot
    ports:
      - "5001:5001"
    networks:
      - traderbot_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Maximum log file size
        max-file: "3"     # Number of log files to retain

  webhook:
    image: denfish/bot-webhook:latest
    volumes:
      - /home/denfish/BotTrader/.env_tradebot:/app/.env_tradebot
      - /home/denfish/BotTrader/data:/app/data
      - /home/denfish/BotTrader/Shared_Utils:/app/Shared_Utils  # Mount the Shared_Utils directory
      - /home/denfish/BotTrader/webhook/webhook_api_key.json
      - /home/denfish/BotTrader/webhook/tb_api_key.json
      - /home/denfish/BotTrader/webhook/websocket_api_key.json
    env_file:
      - ./.env_tradebot
    ports:
      - "5000:5000"
    networks:
      - traderbot_network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  traderbot_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.24.2.0/29"





