name: TradeBot_new
dependencies:
  - python=3.10
  - aiodns
  - aiohttp
  - aiosignal
  - aiosqlite
  - async-timeout
  - attrs
  - Bottleneck
  - ccxt
  - certifi
  - cffi
  - charset-normalizer
  - cryptography
  - frozenlist
  - greenlet
  - idna
  - mkl-fft
  - mkl-random
  - mkl-service
  - multidict
  - numexpr
  - numpy
  - pandas
  - pycares
  - pycparser
  - python-dateutil
  - python-dotenv
  - pytz
  - requests
  - six
  - sqlalchemy
  - tabulate
  - typing_extensions
  - tzdata
  - urllib3
  - yarl
